"""End-to-end scenario, run inside the `hq` container by tests/e2e/run.sh.

HQ   : Oxidized Manager with an embedded Oxidized (workspace 1) that also manages the
       branch installation remotely (workspace 2, manager only — no Oxidized in HQ for it).
Users: admin; ali = operator on workspace 1; veli = viewer and ayse = manager on workspace 2.
Git  : Gitea stands in for GitHub/GitLab — pushes over HTTPS with a token (gitea + github
       providers) and over SSH with a deploy key generated by the manager.
"""
import asyncio
import json
import socket
import sys
import time

import httpx
import websockets

HQ, BR, GITEA = "http://127.0.0.1:8080", "http://branch:8080", "http://gitea:3000"
GUSER, GPASS = "gadmin", "Gitea-pass-123"
passed, failed = 0, 0


def check(name, cond, extra=""):
    global passed, failed
    if cond:
        passed += 1
        print(f"  PASS {name}", flush=True)
    else:
        failed += 1
        print(f"  FAIL {name}  {str(extra)[:600]}", flush=True)
    return cond


def wait(fn, timeout=120, step=2):
    end = time.time() + timeout
    while time.time() < end:
        try:
            r = fn()
            if r:
                return r
        except Exception:  # noqa: BLE001
            pass
        time.sleep(step)
    return None


def set_rev(device, rev):
    with socket.create_connection((device, 9000), timeout=5) as s:
        s.sendall(f"{rev}\n".encode())
        return s.recv(64).decode()


def client(base, user=None, pw=None, lang="en"):
    c = httpx.Client(base_url=base, timeout=60, headers={"X-Lang": lang})
    if user:
        r = c.post("/api/auth/login", json={"username": user, "password": pw})
        assert r.status_code == 200, r.text
    return c


def local_setup(c, name, devices):
    r = c.post("/api/workspaces", json={"type": "local", "name": name, "setup": {
        "username": "admin", "password": "cisco123", "model": "ios", "interval": 3600, "input": "ssh",
        "first_device": {"name": devices[0], "ip": devices[0].lower(), "model": "ios"}}})
    check(f"[{name}] embedded workspace created", r.status_code == 200, r.text)
    for d in devices[1:]:
        r = c.post("/api/w/local/nodes", json={"name": d, "ip": d.lower(), "model": "ios", "group": "core", "fetch_now": True})
        check(f"[{name}] device {d} added", r.status_code == 200, r.text)
    for d in devices:
        c.post(f"/api/w/local/nodes/{d}/fetch")
    for d in devices:
        cfg = wait(lambda d=d: (lambda t: t if f"hostname {d}" in t else None)(c.get(f"/api/w/local/nodes/{d}/config").text), 150)
        check(f"[{name}] {d} backed up by the embedded Oxidized", cfg is not None, c.get(f"/api/w/local/nodes/{d}/config").text[:200])


def gitea_file(g, repo, path, want=""):
    """Reads a file from the main branch (Gitea indexes pushed branches asynchronously, so poll)."""
    def get():
        r = g.get(f"/api/v1/repos/{GUSER}/{repo}/raw/{path}", params={"ref": "main"})
        return r.text if r.status_code == 200 and want in r.text else None
    return wait(get, 20, 1)


def main():
    print("== Gitea (stands in for GitHub / GitLab)")
    gb = httpx.Client(base_url=GITEA, auth=(GUSER, GPASS), timeout=30)
    tok = gb.post(f"/api/v1/users/{GUSER}/tokens", json={"name": f"oxm-{time.time()}", "scopes": ["write:repository", "write:user"]}).json()["sha1"]
    g = httpx.Client(base_url=GITEA, headers={"Authorization": f"token {tok}"}, timeout=30)
    for repo in ("hq-backups", "gh-style", "branch-backups"):
        r = g.post("/api/v1/user/repos", json={"name": repo, "private": True})
        check(f"gitea repo {repo}", r.status_code in (201, 409), r.text)

    print("== Branch installation (embedded Oxidized, managed remotely)")
    b = client(BR)
    check("branch: setup wizard", b.post("/api/setup", json={"username": "admin", "password": "Branch-pass-1"}).status_code == 200)
    local_setup(b, "Branch", ["R3"])
    api_key = b.post("/api/tokens", json={"name": "hq", "scope": "full"}).json()["token"]
    check("branch: API key created", api_key.startswith("oxm_"))

    print("== HQ installation")
    h = client(HQ)
    check("hq: setup wizard", h.post("/api/setup", json={"username": "admin", "password": "Hq-pass-123"}).status_code == 200)
    local_setup(h, "HQ", ["R1", "R2"])
    r = h.post("/api/workspaces", json={"type": "agent", "name": "Branch (remote)", "config": {"url": BR, "token": api_key}})
    check("hq: remote workspace added (HTTPS + API key, no SSH)", r.status_code == 200, r.text)
    ws2 = r.json()["id"]
    check("hq: embedded workspace is unique", h.post("/api/workspaces", json={"type": "local", "name": "x"}).status_code == 409)
    me = h.get("/api/auth/me").json()
    check("hq: remote limit reported (10)", me["max_remote"] == 10 and me["remote_count"] == 1, me)

    print("== Users & sharing")
    users = {}
    for u, access in (("ali", {"local": "operator"}), ("veli", {ws2: "viewer"}), ("ayse", {ws2: "manager"})):
        r = h.post("/api/users", json={"username": u, "password": f"{u}-pass-123", "access": access})
        check(f"user {u} created with access {access}", r.status_code == 200 and r.json()["access"] == access, r.text)
        users[u] = client(HQ, u, f"{u}-pass-123")
    listed = {u: sorted(w["name"] for w in c.get("/api/workspaces").json()) for u, c in users.items()}
    check("ali only sees workspace 1", listed["ali"] == ["HQ"], listed)
    check("veli and ayse only see workspace 2", listed["veli"] == listed["ayse"] == ["Branch (remote)"], listed)
    admin_list = h.get("/api/users").json()
    check("admin panel lists every user with access", {u["username"] for u in admin_list} == {"admin", "ali", "veli", "ayse"})

    ali, veli, ayse = users["ali"], users["veli"], users["ayse"]
    check("ali (operator) adds a device in WS1", ali.post("/api/w/local/nodes", json={"name": "LAB1", "ip": "10.9.9.9", "model": "ios"}).status_code == 200)
    check("ali cannot change Oxidized settings", ali.patch("/api/w/local/config/settings", json={"values": {"interval": 60}}).status_code == 403)
    check("ali cannot open WS2", ali.get(f"/api/w/{ws2}/nodes").status_code == 403)
    check("ali deletes the lab device", ali.delete("/api/w/local/nodes/LAB1").status_code == 200)
    n = veli.get(f"/api/w/{ws2}/nodes").json()["nodes"]
    check("veli (viewer) reads remote devices through the proxy", [x["name"] for x in n] == ["R3"], n)
    check("veli reads the remote config", "hostname R3" in veli.get(f"/api/w/{ws2}/nodes/R3/config").text)
    check("veli cannot add devices", veli.post(f"/api/w/{ws2}/nodes", json={"name": "X", "ip": "1.1.1.1", "model": "ios"}).status_code == 403)
    check("veli cannot reveal secrets", veli.get(f"/api/w/{ws2}/nodes/R3/secrets").status_code == 403)
    check("veli cannot see WS1", veli.get("/api/w/local/nodes").status_code == 403)
    check("ayse (manager) restarts the remote Oxidized", ayse.post(f"/api/w/{ws2}/process/restart").status_code == 200)
    wait(lambda: not ayse.get(f"/api/w/{ws2}/nodes").json().get("api_error"), 60, 1)
    veli_id = next(u["id"] for u in admin_list if u["username"] == "veli")
    check("ayse can share WS2 (veli → operator)", ayse.put(f"/api/workspaces/{ws2}/members", json={"user_id": veli_id, "role": "operator"}).status_code == 200)
    check("veli now may trigger a backup", veli.post(f"/api/w/{ws2}/nodes/R3/fetch").status_code == 200)
    check("ayse cannot manage users", ayse.get("/api/users").status_code == 403)
    audit_remote = b.get("/api/audit").json()
    check("branch audit shows who acted through HQ", any("api:hq (veli)" == a["user"] for a in audit_remote), [a["user"] for a in audit_remote[:5]])

    print("== Backup destinations")
    # WS1 → Gitea (token over HTTPS)
    base = {"branch": "main", "author_name": "Oxidized Manager", "author_email": "oxm@example.com"}
    r = h.post("/api/workspaces/local/destinations/test", json={"type": "gitea", "config": {**base, "server": GITEA, "repo": f"{GUSER}/hq-backups", "token": "wrong"}})
    check("test with a wrong token explains the problem", not r.json()["ok"] and "Authentication failed" in r.json()["error"], r.json())
    rt = h.post("/api/workspaces/local/destinations/test", json={"type": "gitea", "config": {**base, "server": GITEA, "repo": f"{GUSER}/hq-backups", "token": "wrong"}}, headers={"X-Lang": "tr"})
    check("…and in Turkish", "Kimlik doğrulama başarısız" in rt.json()["error"], rt.json())
    cfg1 = {**base, "server": GITEA, "repo": f"{GUSER}/hq-backups", "token": tok, "path": "hq"}
    r = h.post("/api/workspaces/local/destinations/test", json={"type": "gitea", "config": cfg1})
    check("test with the right token", r.json().get("ok") and r.json().get("empty"), r.json())
    r = h.post("/api/workspaces/local/destinations", json={"type": "gitea", "name": "Gitea (token)", "config": cfg1, "interval_min": 60, "run_now": True})
    check("WS1 destination saved and first push started", r.status_code == 200, r.text)
    d1 = r.json()["id"]

    # WS1 → "GitHub" provider pointed at Gitea (exercises the GitHub code path; Gitea accepts x-access-token)
    r = h.post("/api/workspaces/local/destinations", json={"type": "github", "name": "GitHub-style", "interval_min": 0, "run_now": True,
                                                          "config": {**base, "server": GITEA, "repo": f"{GUSER}/gh-style", "token": tok, "path": "", "layout": "flat"}})
    check("WS1 GitHub-provider destination saved", r.status_code == 200, r.text)
    d_gh = r.json()["id"]

    # WS2 (remote) → SSH deploy key generated by the manager, created by ayse (workspace manager)
    k = ayse.post("/api/keygen").json()
    r = g.post(f"/api/v1/repos/{GUSER}/branch-backups/keys", json={"title": "oxidized-manager", "key": k["public_key"], "read_only": False})
    check("deploy key added to the repository", r.status_code == 201, r.text)
    cfg2 = {**base, "url": f"git@gitea:{GUSER}/branch-backups.git", "ssh_key_sealed": k["sealed"], "path": "branch"}
    r = ayse.post(f"/api/workspaces/{ws2}/destinations/test", json={"type": "git_ssh", "config": cfg2})
    check("ayse tests the SSH destination", r.json().get("ok"), r.json())
    r = ayse.post(f"/api/workspaces/{ws2}/destinations", json={"type": "git_ssh", "name": "Gitea (SSH)", "config": cfg2, "interval_min": 60, "run_now": True})
    check("WS2 destination saved by ayse", r.status_code == 200, r.text)
    d2 = r.json()["id"]
    check("veli (operator) cannot edit destinations", veli.post(f"/api/workspaces/{ws2}/destinations", json={"type": "git", "config": {}}).status_code == 403)
    check("ali cannot see WS2 destinations", ali.get(f"/api/workspaces/{ws2}/destinations").status_code == 403)

    def finished(c, wid, did):
        d = next(x for x in c.get(f"/api/workspaces/{wid}/destinations").json() if x["id"] == did)
        return d if not d["running"] and d["last_status"] not in (None, "running") else None

    for c, wid, did, repo, path, want in ((h, "local", d1, "hq-backups", "hq/core/R2", "hostname R2"),
                                         (h, "local", d_gh, "gh-style", "R1", "hostname R1"),
                                         (ayse, ws2, d2, "branch-backups", "branch/R3", "hostname R3")):
        d = wait(lambda c=c, wid=wid, did=did: finished(c, wid, did), 120)
        check(f"push to {repo} succeeded", d and d["last_status"] == "ok", d)
        content = gitea_file(g, repo, path, want)
        check(f"{repo}:{path} contains the config", content and want in content, content)
    check("devices.csv inventory written", gitea_file(g, "hq-backups", "hq/devices.csv", "R1") is not None)
    check("ungrouped device R1 pushed", gitea_file(g, "hq-backups", "hq/R1", "hostname R1") is not None)

    print("== Config change → new version → diff → push")
    first_commit = finished(h, "local", d1)["last_commit"]
    set_rev("r1", 2)
    h.post("/api/w/local/nodes/R1/fetch")
    vers = wait(lambda: (lambda v: v if len(v) >= 2 else None)(h.get("/api/w/local/nodes/R1/versions").json()), 150)
    check("Oxidized stored a new version", vers is not None)
    if vers:
        d = h.get("/api/w/local/nodes/R1/diff", params={"oid": vers[-1]["oid"]}).json()
        check("diff shows the change", "rev2" in d["patch"] and d["added"] >= 1, d.get("patch", "")[:200])
    h.post(f"/api/workspaces/local/destinations/{d1}/run")
    time.sleep(1)
    d = wait(lambda: finished(h, "local", d1), 90)
    check("push after the change created a new commit", d and d["last_status"] == "ok" and d["last_commit"] != first_commit, d)
    check("changed config is in the repository", gitea_file(g, "hq-backups", "hq/R1", "rev2") is not None)
    h.post(f"/api/workspaces/local/destinations/{d1}/run")
    time.sleep(1)
    d = wait(lambda: finished(h, "local", d1), 90)
    check("a run without changes creates no commit", d and d["last_status"] == "unchanged", d)
    runs = h.get(f"/api/workspaces/local/destinations/{d1}/runs").json()
    check("run history recorded", len(runs) >= 3 and runs[0]["status"] == "unchanged", runs[:2])

    print("== Remote change through the proxy + remote live logs")
    set_rev("r3", 7)
    check("veli triggers the remote backup", veli.post(f"/api/w/{ws2}/nodes/R3/fetch").status_code == 200)
    cfg = wait(lambda: (lambda t: t if "rev7" in t else None)(veli.get(f"/api/w/{ws2}/nodes/R3/config").text), 150)
    check("remote Oxidized picked up the change", cfg is not None)
    ayse.post(f"/api/workspaces/{ws2}/destinations/{d2}/run")
    time.sleep(1)
    wait(lambda: finished(ayse, ws2, d2), 90)
    check("remote change pushed over SSH", gitea_file(g, "branch-backups", "branch/R3", "rev7") is not None)

    async def logs():
        cookie = "; ".join(f"{k}={v}" for k, v in veli.cookies.items())
        async with websockets.connect(f"ws://127.0.0.1:8080/api/w/{ws2}/ws/logs?tail=20", additional_headers={"Cookie": cookie}) as ws:
            return json.loads(await asyncio.wait_for(ws.recv(), 15))
    try:
        m = asyncio.run(logs())
        check("remote live log stream via WebSocket", "items" in m and not any(i.get("t") == "error" for i in m["items"]), m)
    except Exception as exc:  # noqa: BLE001
        check("remote live log stream via WebSocket", False, repr(exc))

    print("== Persistence of secrets")
    raw = h.get(f"/api/workspaces/{ws2}/destinations").text + h.get("/api/workspaces").text
    check("no token / key / API key leaks to the browser", tok not in raw and api_key not in raw and "PRIVATE KEY" not in raw)

    print(f"\nRESULT: {passed} passed, {failed} failed")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
